### ISSUE TITLE
Contribution Guide gives 404 page not found

### ISSUE THREAD

**Issue by Nordlenning** [CellularPrivacy/Android-IMSI-Catcher-Detector#857] opened 2016-04-07 10:56 UTC
>Thank you for your feedback! Please add below details so that we can help you a bit faster.

---

#### Agreements
>Please check these boxes to ensure you've actually read and understood these important rules!

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

---

#### Overview
>Please add a short and easy to understand description of the Issue you've experienced here.

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

--- Contribution Guide gives 404 error

#### Reproduction
>Please tell us the detailed steps on how to reproduce your Issue here.

---

#### References
>If your Issue is related to any other existing Issues or pull requests, please link them here.

---

#### Screenshots
>If you experienced visual glitches, please add a screenshot without metadata here.
![screenshot from 2016-04-07 12 50 06](https://cloud.githubusercontent.com/assets/17292772/14348953/3ebc13e0-fcaf-11e5-975f-368c35ff1d74.png)

**Comment by mimi89999** [comment] 2016-04-07 11:01
Duplicate of #840

**Closed** 2016-04-07 11:00 UTC

**Comment by SecUpwN** [comment] 2016-04-07 11:04
Hasn't that been fixed already?
