### ISSUE TITLE
Recheck current cell after OCID download

### ISSUE THREAD

**Issue by DJaeger** [CellularPrivacy/Android-IMSI-Catcher-Detector#558] opened 2015-07-18 12:06 UTC
If you see an "OCID cell not found" notification you will probably download OCID data for your current location. But the notification stays on not found state, as it doesn't recheck existence of current cell after newly imported cells. It only checks against new data after cell change or app restart.

**Reproduce by:**

1. Download BTS-Data
2. State of current cell does not change

The cell is in the OCID database. After restarting the app the state is updated and finds the cell.

**Comment by E3V3A** [comment] 2015-07-19 20:42
This is unclear. Can you please provide instructions for reproducing error? (And suggestions for a fix, if you have it?)

**Comment by SecUpwN** [comment] 2015-07-19 21:09
>Can you please provide instructions for reproducing error?

1. Download the OCID database.
2. AIMSICD shows #349 if the CID has not been uploaded yet (normal).
3. Here is where *this Issue* appears: The CID is does not get checked again!

>But the notification stays on not found state, as it doesn't recheck existence of current cell after newly imported cells. It only checks against new data after cell change or app restart.

@DJaeger, not sure if this Issue is even solvable by us, because if you upload your CID, it needs approval by OCID before it gets added to the database that one can download. Feel free to correct me.

**Comment by E3V3A** [comment] 2015-07-19 21:14
> this Issue is even solvable by us, because if you upload your CID, it needs approval by OCID

Exactly. In addition it takes time for approval, which is very good! So because of this and what we said in #349, we should close this.

**Comment by SecUpwN** [comment] 2015-07-19 21:20
It may be that I did not understand the core problem @DJaeger had. If I misunderstood it, please clarify and add the things @E3V3A requested and we will immediately re-open this. Thank you.

**Comment by DJaeger** [comment] 2015-07-19 21:42
I have never said something of uploading!?

Reproduce by:
1. Download BTS-Data
2. State of current cell does not change

The cell is in the OCID database.
After restarting the app the state is updated and finds the cell.

**Comment by E3V3A** [comment] 2015-07-19 21:48
aah i see now...

**Comment by E3V3A** [comment] 2015-07-19 21:50
It's a similar issue to #284.

**Comment by DJaeger** [comment] 2015-07-19 22:40
Similar, but not the same.

**Comment by DJaeger** [comment] 2015-07-29 16:48
This should do the magic:
```
private CellTracker mCellTracker;
private AimsicdService mAimsicdService;
tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
CellLocation cellLocation = tm.getCellLocation();
mAimsicdService.getCellTracker().compareLac(cellLocation);
```
The compareLac should be called before this line:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/4095f5bf1ef2d4ef1184dab8a294b5aaf62e7dfb/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L329
and before this line:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/4095f5bf1ef2d4ef1184dab8a294b5aaf62e7dfb/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L343

**Comment by SecUpwN** [comment] 2015-07-29 17:30
>This should do the magic...

Thanks, @DJaeger! Are you able to also *add* the magic? :smile_cat:

**Comment by E3V3A** [comment] 2015-08-04 10:18
@DJaeger  I get a `Fatal Exception` in Main, due to NPE in RequestTask.java:337 and 98...
I already said this FC'd in your last PR, and I can't see you changed anything since then..

**Comment by E3V3A** [comment] 2015-08-04 11:47
We probably need to add some `try() / catch()` there...to see better what's going on.

**Comment by DJaeger** [comment] 2015-08-04 17:52
Of course I changed the code before I pulled again.
With my last change it was able to successfully build, but I wasn't able to test the download, as my emulator was damaged.
I'm sorry.

**Comment by E3V3A** [comment] 2015-08-05 11:30
Sound great!

**Comment by SecUpwN** [comment] 2015-08-09 18:04
Hey @DJaeger, are you still on it to give this yet another shot including a `try() / catch()`? ;-)

**Comment by DJaeger** [comment] 2015-08-09 18:20
Of cause, as soon as my time allows it.
I'm not gone away. ;-)

**Comment by E3V3A** [comment] 2015-08-21 16:24
@DJaeger Can we still count on you looking into this?

**Comment by E3V3A** [comment] 2015-08-25 04:37
@marvinmarnold It will be hard to merge anything external, if simple bugs like this cannot be handled...

**Comment by DJaeger** [comment] 2015-08-25 07:37
@E3V3A: As I already said, I will do so, but I have a project to be completed this week that has to be priorized.

**Comment by SecUpwN** [comment] 2015-08-25 07:39
Thanks, take all the time you need, @DJaeger. A short statement like this keeps us motivated. :)

**Closed** 2016-03-26 18:40 UTC
Labels: BUG
