### ISSUE TITLE
App quits when retrieving OpenCellID key

### ISSUE THREAD

**Issue by lop1** [CellularPrivacy/Android-IMSI-Catcher-Detector#691] opened 2015-12-20 14:05 UTC
If in preferences you try to get an opencellID key you got : 
"Android IMSI-Catcher Detector stopped"

release 0.1.37 alpha
galaxy S4 mini
stock rom rooted ( COJ1 )

**Comment by SecUpwN** [comment] 2015-12-20 14:47
Possibly related to #688. Please wait for this to be fixed. Thank you.

**Comment by SecUpwN** [comment] 2016-03-30 01:04
@larsgrefer, this bug is present again after your latest changes.

**Comment by mimi89999** [comment] 2016-04-05 19:46
I can't reproduce it.

**Comment by mimi89999** [comment] 2016-04-05 19:51
I think this was fixed in https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/commit/76bc831faa7fe8514cd4663e82753a2a7a9b170d

**Closed** 2016-04-05 19:53 UTC
Labels: bug
