### ISSUE TITLE
Crashing when Downloadinh Data

### ISSUE THREAD

**Issue by FFY00** [CellularPrivacy/Android-IMSI-Catcher-Detector#939] opened 2017-08-19 02:07 UTC
### Agreements

- [x] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview

* `AIMSICD` version (see the `About` screen): v0.1.43-alpha-normal
* Phone and ROM running *current* release: Xiaomi Redmi Note 4 running MIUI 8 8.5 (Android 7.0)
* Link to logfile without identifyable data: Error below
```
java.lang.IllegalArgumentException: Field 'cell' does not exist.
	at io.realm.RealmObjectSchema.getColumnIndices(RealmObjectSchema.java:574)
	at io.realm.RealmQuery.lessThan(RealmQuery.java:734)
	at com.secupwn.aimsicd.utils.RealmHelper$3.execute(RealmHelper.java:422)
	at io.realm.Realm.executeTransaction(Realm.java:1109)
	at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:301)
	at com.secupwn.aimsicd.utils.RequestTask.onPostExecute(RequestTask.java:81)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6195)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
```

### Reproduction

Just clicking in 'Download BTS Data'. I have a token from Unwired Labs (I think that's the api key requested, but not sure¿).

### References

Upload Data worked just once, after that I get the usuall error dialog.

### Screenshots

Nothing needed.

**Comment by beerisgood** [comment] 2017-08-19 06:08
Project isnt active any longer.
See https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues/926

**Comment by Nordlenning** [comment] 2017-10-12 21:07
Field 'cell' does not exist.

Duplicate of  #899 Please close.

**Closed as completed** 2017-10-14 07:12 UTC
