### ISSUE TITLE
Don't turn on the GPS when cell tracking is off

### ISSUE THREAD

**Issue by quantum1423** [CellularPrivacy/Android-IMSI-Catcher-Detector#764] opened 2016-02-04 16:39 UTC
AIMSICD turns on the GPS even when I have the cell tracking off. This drains a lot of battery, and puts an ugly notification on the top bar.

I just want AIMSICD to buzz my phone when it detects an attack; I usually can remember where I was when the attack occurred if it's logged with a timestamp. I don't need it to remember the locations of IMSI catchers etc.

**Comment by vanitasvitae** [comment] 2016-02-05 06:47
Have you tried to remove the App from the list of recently started apps by swiping it out of the recent apps view after changing the settings? I guess AIMSICD only applies changed settings after been "soft-killed" in this way.

**Comment by SecUpwN** [comment] 2016-02-05 07:41
Thanks for notifying, @quantum1423. Is your Issue a duplicate of the already fixed #251?

**Comment by quantum1423** [comment] 2016-02-06 03:53
No, I don't think it's the same issue. I'm not trying to turn off GPS globally; I just want AIMSICD not to turn on the GPS unless it needs to log locations.

**Comment by NezSpencer** [comment] 2016-02-15 08:43
@quantum1423 hope you really dont mind but could you expatiate on what you want AIMSICD to do? 
I dont think AIMSICD turns on GPS automatically, the user is prompted to turn on GPS at launch of the app. Are you saying you want GPS to be turned off when cell tracking is disabled?

**Comment by quantum1423** [comment] 2016-02-15 21:40
> Are you saying you want GPS to be turned off when cell tracking is disabled? 
Yes.

**Comment by PlNG** [comment] 2016-02-16 05:45
What about passively listening for cell towers (the way llama does), and actively making a GPS request when a possible attack or new tower is detected?

**Comment by NezSpencer** [comment] 2016-02-16 07:20
@SecUpwN wht do you think?

**Comment by SecUpwN** [comment] 2016-02-16 14:06
>What about passively listening for cell towers (the way llama does), and actively making a GPS request when a possible attack or new tower is detected?

Sounds like a great solution, both on battery life and privacy. But since our app is currently still in bleeding `ALPHA` stage and stays in yellow mode most of the time due to missing detection methods, I'm not sure if these changes are possible yet. Maybe we should combine these settings with #15?

I'd like @larsgrefer and @He3556 to have a word about this here as well. I feel as if our in-app `Preferences`are already pretty heavy on the user. And as long as we have no initial configuration like #181 when starting our app the first time, my guess is that users will have yet another confusion. In general, I guess our app needs a much cleaner and easier re-design with proposed #258 in the long run.

**Comment by He3556** [comment] 2016-02-16 21:24
yes i think this is really annoying and i don't know why we did it this way. I remember some discussion we had with EVA about it. But when Cell tracking is switched off - why would we need GPS? 

The yellow alarm is a problem on a few phones but not all. On my HTC i never had this issue. We could fix these false alarms if some developer had time for it right now...

Sorry but what is llama?

**Comment by SecUpwN** [comment] 2016-02-27 10:50
@quantum1423, is your bug still present within our current release?

**Comment by PlNG** [comment] 2016-02-27 18:03
@He3556 "Llama - Location Profiles" by Kebabapps, an app that provides mobile event scripting.

**Comment by SecUpwN** [comment] 2016-03-22 02:06
>@quantum1423, is your bug still present within our current release?

I am closing this Issue due to **poor maintenance**. It has likely been solved. Please re-open if it isn't.

**Closed by SecUpwN** 2016-03-22 02:06 UTC
Labels: BUG
