### ISSUE TITLE
Why are there 20 Base Transceiver Stations at my house?

### ISSUE THREAD

**Issue by OpR8R** [CellularPrivacy/Android-IMSI-Catcher-Detector#919] opened 2017-03-29 22:47 UTC
### Agreements

- [x ] **I have reviewed and accepted the [guidelines for contributing](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md) to this project.**
- [x ] **I have searched the [open Issues](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/issues) and made sure I am not filing a duplicate.**
- [x ] **I have read the notes on [debugging](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/blob/development/.github/CONTRIBUTING.md#debugging) and will properly maintain this Issue.**

### Overview
AIMSICD v0.1.43-alpha-normal, build numberT-1939,
Samsung SM-G900V, build number MMB29M.G900VVRU2DPJ2

I am reasonably confident that I have screened for a duplicate issue and found none, and like I read a previous poster say, I am not necessarily tech savvy but I need some help:

1. Every place my daughter and I stay for any length of time, within days/weeks there are anywhere from 12-20 new "bts" indications present in the Antenna Map Viewer, all of them on the property and most within the "footprint" of the house itself. My understanding is that a base transceiver station is, for all intents and purposes, either a cell tower or essentially functioning as a cell tower. Am I correct? If so, why are there 20 of them whatever I go? 

* `AIMSICD` version (see the `About` screen):
* Phone and ROM running *current* release:
* Link to logfile without identifyable data:

### Reproduction
Ummm, come to this house and turn on Aimsicd? Best I can tell ya anyway.

### Screenshots
![example 1](https://cloud.githubusercontent.com/assets/13159413/24479973/c916c904-1496-11e7-996d-f18effdca37f.png)

**Comment by Nordlenning** [comment] 2017-03-30 02:15
This looks like a duplicate of #471, please take a look..

**Comment by OpR8R** [comment] 2017-03-30 03:27
>This looks like a duplicate of #471, please take a look..

Thank you and it's similar, I agree, except that all of mine are **at my house**, most of them apparently within the perimeter of my home's footprint. Someone (arleslie) did contribute to the thread with a screenshot of multiple BTSs right on top of his house like my situation but I don't see that anyone addressed that question/example; it seems to have quickly degenerated into a bit of a squabble between the "yay" and "nay" camps of AIMSICD fans. So, yes, the thread does address multiple connections but doesn't address my main area of concern; namely that there's 20 of them and they're all on my property and this occurs wherever I live within days/weeks.

**Comment by Nordlenning** [comment] 2017-03-30 03:41
Do all the measurements (bluecells) have the same CellID ? They could be multiple new measurements of a well known or new locally stored BTS.

My conclusion was in 471 ;" All these "Bluecells" "[blue circle] currently connected BTS". is actually new collected measurements or new discovered BTS, They should (could) be labeled "Orange" Then they would be correct.. All of them states O samples,
@SecUpwN states "Sounds like some smaller part of our code to classify new collected cells is messed up"..

**Comment by OpR8R** [comment] 2017-03-31 00:23
Hi and thanx. No, in fact, they all have unique identifiers/CIDs. And again, if my daughter and I move to a new location we always make note of what BTSs are there (which is always zero), and within days to a few weeks the number steadily grows to anywhere from 12 to 20, all unique, all shown connected to our devices. We've tested this on any number of different phones/devices and with any number of AIMSICD releases. Always the same result. There's other stuff happening to us as well but I will refrain from discussing that as it is not within the purview of this board's area of interest. I mostly need to understand what these things (BTS) ARE, and what they AREN'T. Speaking of CIDs and other identifiers, many are oddball or are missing information (I've attached a few samples of the pop-ups you get when you tap the cells on the map). Others come and go but there are several CIDs that have shown up consistently wherever we go. Interestingly (or not, I have little knowledge in this field) the PSC is nearly always "unknown."

PS: All those LAT/LONs you see? They're all on this property, I checked the LAT/LON or our parcel's 4 corners with the county and all these BTSs coordinates are within the parcel boundaries. So, that's weird, right?
 
![example 1 4](https://cloud.githubusercontent.com/assets/13159413/24531343/27cedc80-156d-11e7-8f0f-32b0ed45150f.png)

![example 1 1](https://cloud.githubusercontent.com/assets/13159413/24531207/0faea0c8-156c-11e7-88a1-8cca3bf68ae7.png)
![example 1 2](https://cloud.githubusercontent.com/assets/13159413/24531289/b0686576-156c-11e7-8d90-4831204aee96.png)
![example 1 3](https://cloud.githubusercontent.com/assets/13159413/24531296/ba173534-156c-11e7-9bdd-d0853b5c0b72.png)

**Comment by Nordlenning** [comment] 2017-03-31 02:24
Hi  @OpR8R 

What I think is happening in your case is that every-time you visit one
place regular, new "Bluecells" will be added to the Map & the internal db as new msm.
They should not be displayed on the map, just in the internal db as new msm. (This is the bug)
If we renamed these blucells on the map to say "New collected Measurements" They would be correct.
These "Blucells" represent your phones location when msm are collected. NOT the location of the BTS/Antena. 
That's why there may be many in one place (if you stay for a long time in one place).

There are several treads regarding CID LTE/3G etc.. LTE cell does not have PSC if I remember correct,
3G do.. Data uses LTE, Voice uses 3G. BTS is the Antenna your phone connects to. Cell is a collection of several BTS/Antennas. One BTS may be used by several Cells.

https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki/Glossary-of-Terms
is a very nice place to start.

So if you are on your property & only one BTS/Antenna is in sigth, you could get 2 different CID.
One unique CID for the 3G Cell & One for the LTE .
 
If your phone is in waiting stage it may be connected to the LTE cell, If you make/receive a call it gets downgraded to 3G. Your picture shows 2 different CID,  3G/LTE, that is correct.

"PS: All those LAT/LONs you see? They're all on this property" This tells me that my thinking may be correct.

"in fact, they all have unique identifiers/CIDs"
"the number steadily grows to anywhere from 12 to 20, all unique"

But if all of these bluecells on your property have different CID, I don't have a clue..

This statment tell me that you have 20 or more "bluecells" with different CID on the same GPS coordinates.

Please remember that this app is still in Alpha stage  & bugs will appeare, & hopfullly dissapeare..

**Comment by OpR8R** [comment] 2017-03-31 19:10
Thank you very much for your input and help, I am learning more and more as I go along. Unfortunately your last observation...
> But if all of these bluecells on your property have different CID, I don't have a clue..

... is indeed the case; all have distinct and unique CIDs.

So let me make sure I have this right; the bluecells that appear on the map are the location of MY device (phone) when a new "msm" (measurement?) is made? If so, that is new information to me, so that's a good thing. It may turn out that if it's a bug that's allowing all these bluecells to remain on the map it's been a helpful bug because it's what alerted us to the situation to begin with.

**New question: if money were no object, is there any way/gear to determine the location of the BTS(s)?**

**Comment by Nordlenning** [comment] 2017-10-15 20:26
Please close

**Closed as completed** 2017-10-16 22:27 UTC
